# Generated by Django 5.0.7 on 2024-08-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Canceled Order',
                'verbose_name_plural': 'Canceled Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
            ],
            options={
                'verbose_name': 'New Order',
                'verbose_name_plural': 'New Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
